"""
Event shapes accepted by the ingestion API.

This is the contract with the SDK. The SDK has a matching definition in
`sdk/tracelens/events.py`; keep the two in step. (A shared package would remove
the duplication, but it would also couple the SDK's release cycle to this
service's, which is the wrong trade while both are moving.)
"""

import uuid
from datetime import datetime
from typing import Annotated, Any, Literal

from pydantic import BaseModel, ConfigDict, Field, model_validator

Status = Literal["success", "error", "cancelled"]


class InferenceEvent(BaseModel):
    """
    One LLM call, as observed by the SDK.

    `extra="ignore"` on purpose: a newer SDK sending a field this service doesn't
    know about should still have its event accepted, not rejected. Forward
    compatibility matters more here than strictness, because the SDK is deployed
    inside someone else's application and can't be upgraded in lockstep.
    """

    model_config = ConfigDict(extra="ignore")

    # --- identity ---------------------------------------------------------
    # Generated by the SDK so retries are idempotent: the worker can upsert on
    # this and a re-delivered event won't double-count.
    event_id: uuid.UUID
    service: Annotated[str, Field(max_length=100)]
    sdk_version: Annotated[str, Field(max_length=20)] = "unknown"

    # --- what was called --------------------------------------------------
    provider: Annotated[str, Field(max_length=50)]
    model: Annotated[str, Field(max_length=100)]
    operation: Annotated[str, Field(max_length=50)] = "chat.completions"
    streaming: bool = False

    # --- outcome ----------------------------------------------------------
    status: Status
    error_type: Annotated[str | None, Field(max_length=100)] = None
    error_message: Annotated[str | None, Field(max_length=2000)] = None

    # --- timing -----------------------------------------------------------
    started_at: datetime
    ended_at: datetime
    latency_ms: Annotated[int, Field(ge=0)]
    # Only meaningful for streamed calls, and the more useful number for
    # perceived responsiveness than total latency.
    time_to_first_token_ms: Annotated[int | None, Field(ge=0)] = None

    # --- usage ------------------------------------------------------------
    # Nullable throughout: a failed call has no usage, and a streamed call only
    # reports it if the caller asked for it.
    prompt_tokens: Annotated[int | None, Field(ge=0)] = None
    completion_tokens: Annotated[int | None, Field(ge=0)] = None

    # --- correlation ------------------------------------------------------
    conversation_id: Annotated[str | None, Field(max_length=64)] = None
    session_id: Annotated[str | None, Field(max_length=64)] = None
    user_id: Annotated[str | None, Field(max_length=64)] = None
    request_id: Annotated[str | None, Field(max_length=64)] = None

    # --- content ----------------------------------------------------------
    # Previews only, already truncated and redacted by the SDK. Storing full
    # prompts would make this database a liability; a preview is enough to
    # recognise a request while debugging.
    input_preview: Annotated[str | None, Field(max_length=1000)] = None
    output_preview: Annotated[str | None, Field(max_length=1000)] = None
    message_count: Annotated[int | None, Field(ge=0)] = None

    metadata: dict[str, Any] = Field(default_factory=dict)

    @property
    def total_tokens(self) -> int | None:
        if self.prompt_tokens is None and self.completion_tokens is None:
            return None
        return (self.prompt_tokens or 0) + (self.completion_tokens or 0)

    @model_validator(mode="after")
    def _check_timing(self) -> "InferenceEvent":
        """
        Reject events whose clock doesn't make sense.

        A negative duration means a bug or a tampered payload, and either way it
        would poison latency percentiles for the whole bucket.
        """
        if self.ended_at < self.started_at:
            raise ValueError("ended_at is before started_at")
        return self


class EventBatch(BaseModel):
    """
    A batch of events.

    Capped so one request can't be used to exhaust memory. The SDK batches to
    roughly 50, so 500 leaves ample headroom.
    """

    events: Annotated[list[InferenceEvent], Field(min_length=1, max_length=500)]


class RejectedEvent(BaseModel):
    """Which event failed validation, and why."""

    index: int
    error: str


class IngestResponse(BaseModel):
    """
    Result of an ingestion request.

    Reports accepted and rejected counts separately rather than failing the whole
    batch on one bad event — otherwise a single malformed event would make the SDK
    retry the batch forever and lose all the good events with it.
    """

    accepted: int
    rejected: int = 0
    errors: list[RejectedEvent] = Field(default_factory=list)


class StatsResponse(BaseModel):
    """Aggregate over what's currently buffered. A stand-in until rollups exist."""

    total_events: int
    buffered_events: int
    error_count: int
    error_rate: float
    avg_latency_ms: float | None
    p95_latency_ms: float | None
    by_model: dict[str, int]
    by_status: dict[str, int]
