"""
Pydantic request and response models.

These mirror `frontend/src/types/index.ts` exactly. The frontend is the contract:
if a field name changes here it must change there too, or the UI silently reads
`undefined`.
"""

import json
import uuid
from datetime import datetime
from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, EmailStr, Field

from models import MessageRole, MessageStatus

# Matches the frontend's client-side check in AuthForm.tsx. Keep them in step, or
# users get a server error for something the form said was fine.
Password = Annotated[str, Field(min_length=8, max_length=128)]


class ORMModel(BaseModel):
    """Base for responses built directly from SQLAlchemy objects."""

    model_config = ConfigDict(from_attributes=True)


# --- auth -----------------------------------------------------------------


class RegisterRequest(BaseModel):
    email: EmailStr
    password: Password


class LoginRequest(BaseModel):
    email: EmailStr
    password: str


class GuestRequest(BaseModel):
    """
    Device id generated by the browser (frontend/src/lib/device.ts).

    Length-capped because it goes straight into a unique indexed column and is
    attacker-controlled.
    """

    device_id: Annotated[str, Field(min_length=8, max_length=64)]


class UpgradeGuestRequest(BaseModel):
    email: EmailStr
    password: Password


class UserOut(ORMModel):
    id: uuid.UUID
    email: str | None
    is_guest: bool
    created_at: datetime


class TokenResponse(BaseModel):
    access_token: str
    token_type: Literal["bearer"] = "bearer"
    user: UserOut


# --- conversations --------------------------------------------------------


class ConversationCreate(BaseModel):
    """Title is optional — the frontend derives one from the first message."""

    title: Annotated[str, Field(min_length=1, max_length=200)] | None = None


class ConversationUpdate(BaseModel):
    title: Annotated[str, Field(min_length=1, max_length=200)]


class ConversationSummary(ORMModel):
    """Sidebar row. `message_count` is computed, not a column."""

    id: uuid.UUID
    title: str
    created_at: datetime
    updated_at: datetime
    message_count: int = 0


class MessageOut(ORMModel):
    id: uuid.UUID
    conversation_id: uuid.UUID
    role: MessageRole
    content: str
    created_at: datetime
    model: str | None = None
    status: MessageStatus = MessageStatus.COMPLETE
    # Read from the ORM attribute `error_message`, emitted as `error` because
    # that's the key the frontend's Message type reads. A serialization_alias
    # rather than a validation_alias so from_attributes still finds the column;
    # FastAPI serialises responses with by_alias=True, so the output key is right.
    error_message: str | None = Field(default=None, serialization_alias="error")


class ConversationDetail(ConversationSummary):
    messages: list[MessageOut] = []


class MessageCreate(BaseModel):
    content: Annotated[str, Field(min_length=1, max_length=32_000)]


# --- SSE stream events ----------------------------------------------------
#
# The frontend's toStreamEvent (frontend/src/api/chat.ts) reads the `type` field
# inside the payload and also accepts the SSE event name, so `to_frame()` sets
# both. Emitting only one of the four shapes below will leave the UI's assistant
# bubble stuck in its streaming state.


class StreamEvent(BaseModel):
    type: str

    def to_frame(self) -> str:
        """
        Render as an SSE frame.

        The trailing blank line is the frame terminator and is not optional —
        without it the client buffers forever waiting for the delimiter.
        """
        payload = json.dumps(self.model_dump(mode="json"))
        return f"event: {self.type}\ndata: {payload}\n\n"


class StreamStart(StreamEvent):
    type: Literal["start"] = "start"
    conversation_id: uuid.UUID
    message_id: uuid.UUID
    model: str


class StreamDelta(StreamEvent):
    type: Literal["delta"] = "delta"
    text: str


class StreamDone(StreamEvent):
    type: Literal["done"] = "done"
    message_id: uuid.UUID
    finish_reason: str | None = None
    prompt_tokens: int | None = None
    completion_tokens: int | None = None


class StreamError(StreamEvent):
    type: Literal["error"] = "error"
    message: str
